version: '3'

services:

  producer:
    image: producer:latest
    ports:
      - "8081:8282"
    depends_on:
      - kafka
    networks:
      - test

  consumer:
    image: consumer:latest
    ports:
      - "8082:8383"
    depends_on:
      - kafka
    networks:
      - test

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    expose:
      - "2181"
    networks:
      - test

  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
    networks:
      - test

networks:
  test: